version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "8001:8001"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    shm_size: "1gb" 
    cap_add:
      - SYS_ADMIN 
    security_opt:
      - seccomp:unconfined 

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
